name: Build
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
      - RotatingLabelTests/**/*
      - '**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
      - RotatingLabelTests/**/*
      - '**/*.swift'
jobs:
  build:
    timeout-minutes: 15
    runs-on: macos-12
    steps:
      - name: checkout dist
        uses: actions/checkout@v3
        with:
          # git-restore-mtime-bare uses the ref log to find the correct timestamp
          # for each file. This requires a full git history. The default value (1)
          # creates a shallow checkout.
          fetch-depth: 0
      - name: restore timestamps
        uses: chetan/git-restore-mtime-action@v2
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-v3-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-v3-
      - name: Prep
        run: defaults write com.apple.dt.XCBuild IgnoreFileSystemDeviceInodeChanges -bool YES
      - name: Build iOS
        run: make build_ios
      - name: Build tvOS
        run: make build_tvos
      - name: Run tests
        run: make test
