name: Build
on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
      - RotatingLabelTests/**/*
      - '**/*.swift'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/build.yml'
      - RotatingLabelTests/**/*
      - '**/*.swift'
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-build-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Build iOS
        run: make build_ios
      - name: Build tvOS
        run: make build_ios
      - name: Run tests
        run: make test
